title: American Viticultural Areas Digitizing Project
description: AVA boundaries in spatial format brought to you by the UC Davis Library & UC Davis DataLab

remote_theme: carlosperate/jekyll-theme-rtd

# Specific to this theme
# site_author: 
repo_url: 'https://github.com/UCDavisLibrary/ava'
edit_on_github: true
github_docs_folder: true
#logo: 'https://your.url/image.png'
#site_favicon: 'https://your.url/here.ico'
sticky_navigation: true
prev_next_buttons_location: None
prev_next_buttons_location: top
prev_next_buttons_location: bottom
prev_next_buttons_location: both
search_enabled: true
#google_analytics: UA-XXXXX-Y
#google_analytics_anonymize_ip: true
# The highlight.js library provides 79 different colours for their syntax highlighting. The default is github-gist.
hljs_style: github-gist