title: American Viticultural Areas Digitizing Project
description: AVA boundaries in spatial format brought to you by the UC Davis Library & UC Davis DataLab

remote_theme: pmarsceill/just-the-docs


color_scheme: ucdcolors