# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "jekyll", "~> 4.2"

group :jekyll_plugins do
  gem "jekyll-remote-theme", "~> 0.4.3"
  gem "just-the-docs", "~> 0.3.3"
end

gem 'wdm', '>= 0.1.0' if Gem.win_platform?
gem "webrick", "~> 1.7"
